%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\gabri\Dropbox\AgroModel\fechasiembra.xlsx
%    Worksheet: Soja
%
% Auto-generated by MATLAB on 16-Feb-2022 13:57:17

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = "Soja";
opts.DataRange = "A1:H60";

% Specify column names and types
opts.VariableNames = ["campo", "Lote", "lat", "long", "variedad", "antecesor", "FS", "RtoTn"];
opts.VariableTypes = ["char", "char", "char", "char", "char", "char", "char", "char"];

% Specify variable properties
opts = setvaropts(opts, ["campo", "Lote", "lat", "long", "variedad", "antecesor", "FS", "RtoTn"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["campo", "Lote", "lat", "long", "variedad", "antecesor", "FS", "RtoTn"], "EmptyFieldRule", "auto");

% Import the data
fechasiembra = readtable("C:\Users\gabri\Dropbox\AgroModel\fechasiembra_2021-2022.xlsx", opts, "UseExcel", false);

%% Convert to output type
fechasiembra = table2cell(fechasiembra);
numIdx = cellfun(@(x) ~isnan(str2double(x)), fechasiembra);
fechasiembra(numIdx) = cellfun(@(x) {str2double(x)}, fechasiembra(numIdx));

%% Clear temporary variables
clear opts


%% Matriz de coordenadas decimles y fechas de siembra
% limpieza de lat y longitud
mat_coord_s = [];
mat_fs_s = [];
for i = 2 : size(fechasiembra,1)
    tmp = cell2mat(fechasiembra(i,3));
    lat = str2angle( strcat(tmp(1:8),'"S'));
    tmp = cell2mat(fechasiembra(i,4));
    lon = str2angle( strcat(tmp(1:8),'"W'));


    t = datetime(cell2mat(fechasiembra(i,7)),'InputFormat','dd-MMM-yyyy','Format','yyyy-MM-dd');
    mat_coord_s = [mat_coord_s; lat,lon];
    mat_fs_s = [mat_fs_s;t];
end

clear tmp lat lon t