%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\gabri\Dropbox\AgroModel\campana2020-2021\Solar radiation 011020 to 310521.csv
%
% Auto-generated by MATLAB on 2022-05-23

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["YEAR", "Var2", "mjm2", "Month", "Day"];
opts.SelectedVariableNames = ["YEAR", "mjm2", "Month", "Day"];
opts.VariableTypes = ["double", "string", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Var2", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var2", "EmptyFieldRule", "auto");

% Import the data
Solarradiation011020to310521 = readtable("C:\Users\gabri\Dropbox\AgroModel\campana2020-2021\Solar radiation 011020 to 310521.csv", opts);


%% Clear temporary variables
clear opts