%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\gabri\Dropbox\AgroModel\Meteorology\EstacionObservado_20220312_20220807.xlsx
%    Worksheet: Hoja1
%
% Auto-generated by MATLAB on 2022-05-01

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 13);

% Specify sheet and range
opts.Sheet = "Hoja1";
opts.DataRange = "A2:M40094";

% Specify column names and types
opts.VariableNames = ["Fecha", "Time", "Temperatura", "TempRocioC", "HumRel", "VVDD", "VVFFkmh", "Vvrafkmh", "PresionhPa", "PPRatemm", "PPAcummm", "UV", "Solarwm2"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "VVDD", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Fecha", "InputFormat", "");

% Import the data
datosObservados2 = readtable("Meteorology\EstacionObservado_20220312_20220807.xlsx", opts, "UseExcel", false);

%% Clear temporary variables
clear opts


formafecha = 'dd-MMM-yyyy';
t1 = table2array(datosObservados2(1,1));
% fecha final
t2 = table2array(datosObservados2(end,1));

fechas =(t1:t2)';
nueva_matriz = [];
for d = 1:length(fechas)
    dia = fechas(d);
    idx = find(datosObservados2.Fecha==dia);
    aux = 1;
    while isempty(idx)
        idx = find(datosObservados2.Fecha==fechas(d-aux));
        aux = aux +1;
    end
    temp_min = min(datosObservados2.Temperatura(idx));
    temp_med = mean(datosObservados2.Temperatura(idx));
    temp_max = max(datosObservados2.Temperatura(idx));
    
    hr_min = min(datosObservados2.HumRel(idx));
    hr_max = max(datosObservados2.HumRel(idx));
    
    prec = max(datosObservados2.PPAcummm(idx)); 
    
    rad = sum(datosObservados2.Solarwm2(idx))/288; 
    
    evap = 0.0023*(temp_med+17.78)*(rad/(11.574074074074074*2.45))*((temp_max-temp_min)^0.5);
    
    helada_tmp = datosObservados2.Temperatura(idx);
    helada_vto = datosObservados2.VVFFkmh(idx);
    
    helada_diaria =  double((helada_tmp<1).*(helada_vto<10));
    if sum(helada_diaria)>2
        helada = 1;
    else
        helada = 0;
    end
    
    duracion_helada = floor(sum(helada_diaria)/12);
    
    if ~isempty(idx)    
        nueva_matriz = [nueva_matriz;temp_min,temp_med,temp_max,hr_min,hr_max,prec,rad/11.574074074074074,evap,helada,duracion_helada];
    else
        nueva_matriz = [nueva_matriz;nueva_matriz(end,:)];
    end
    

end

% datosObservados2 = timetable(fechas,nueva_matriz(:,1:9),...
%     'VariableNames',{'tmpmin','tmpmed','tmpmax','hrmin','hrmax','precip','RAD','ET0','HELADA'});
datosObservados2 = timetable(fechas,nueva_matriz(:,1),nueva_matriz(:,2),...
    nueva_matriz(:,3),nueva_matriz(:,4),nueva_matriz(:,5),nueva_matriz(:,6),nueva_matriz(:,7),nueva_matriz(:,8),nueva_matriz(:,9),nueva_matriz(:,10),...
    'VariableNames',{'tmpmin','tmpmed','tmpmax','hrmin','hrmax','precip','RAD','evap','HELADA','DUR_HELADA'});