%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\gabri\Dropbox\AgroModel\Meteorology\20220424_salidaPronosticoClimatico.csv
%
% Auto-generated by MATLAB on 2022-05-09

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["VarName1", "TMINC", "TMEDC", "TMAXC", "HR_MIN", "HR_MAX", "RADMJM2", "LLUVIAmm", "TTDC", "GRANIZO", "COND_HELADAS", "FECHA"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
climafuturo = readtable("C:\Users\gabri\Dropbox\AgroModel\Meteorology\20220424_salidaPronosticoClimatico.csv", opts);


%% Clear temporary variables
clear opts