%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\gabri\Dropbox\AgroModel\Meteorology\salidaPronoticoClimatico.csv
%
% Auto-generated by MATLAB on 2022-05-01

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 10);

% Specify range and delimiter
opts.DataLines = [2, 87];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["VarName1", "TMINC", "TMEDC", "TMAXC", "RADMJM2", "LLUVIAmm", "TTDC", "GRANIZO", "COND_HELADAS", "FECHA"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "datetime"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "FECHA", "InputFormat", "yyyyMMdd","DatetimeFormat","yyyy-MM-dd");

% Import the data
salidaPronosticoClimatico = readtable("C:\Users\gabri\Dropbox\AgroModel\Meteorology\salidaPronoticoClimatico.csv", opts);


%% Clear temporary variables
clear opts