%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\gabri\Dropbox\AgroModel\fechasiembra.xlsx
%    Worksheet: Maiz
%
% Auto-generated by MATLAB on 16-Feb-2022 14:33:50

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 10);

% Specify sheet and range
opts.Sheet = "Maiz";
opts.DataRange = "A1:J52";

% Specify column names and types
opts.VariableNames = ["campo", "VarName2", "lat", "long", "Hibrido", "antecesor", "FS", "FS_CORR", "RtoTn", "VarName10"];
opts.VariableTypes = ["categorical", "char", "char", "char", "char", "char","char","char", "char", "char"];

% Specify variable properties
opts = setvaropts(opts, ["VarName2", "lat", "long", "Hibrido", "antecesor", "RtoTn", "VarName10"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["campo", "VarName2", "lat", "long", "Hibrido", "antecesor", "RtoTn", "VarName10"], "EmptyFieldRule", "auto");
% opts = setvaropts(opts, "FS", "InputFormat", "");

% Import the data
fechasiembra = readtable("fechasiembra_2021-2022.xlsx", opts, "UseExcel", false);

%% Convert to output type
fechasiembra = table2cell(fechasiembra);
numIdx = cellfun(@(x) ~isnan(str2double(x)), fechasiembra);
fechasiembra(numIdx) = cellfun(@(x) {str2double(x)}, fechasiembra(numIdx));


%% Clear temporary variables
clear opts


%% Matriz de coordenadas decimles y fechas de siembra
% limpieza de lat y longitud
mat_coord_m = [];
mat_fs_m = [];
for i = 2 : size(fechasiembra,1)
    tmp = cell2mat(fechasiembra(i,3));
    lat = str2angle( strcat(tmp(1:8),'"S'));
    tmp = cell2mat(fechasiembra(i,4));
    lon = str2angle( strcat(tmp(1:8),'"W'));
    t = datetime(cell2mat(fechasiembra(i,8)),'InputFormat','dd-MMM-yyyy','Format','yyyy-MM-dd');
    mat_coord_m = [mat_coord_m ; lat,lon];
    mat_fs_m = [mat_fs_m ; t];
end
% cell_fs_m = cell(0);
% for i = 1:size(mat_fs_m,1)
%     cell_fs_m{i}=mat_fs_m(i,:);
% end

clear tmp lat lon t