%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\gabri\Dropbox\AgroModel\Meteorology\PAR 301121 al 170122.xlsx
%    Worksheet: PAR
%
% Auto-generated by MATLAB on 2022-05-09

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = "PAR";
opts.DataRange = "A2:E49";

% Specify column names and types
opts.VariableNames = ["YEAR", "DOY", "DIA", "MES", "PARMJM2"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Import the data
radhist_3 = readtable("Meteorology\PAR 301121 al 170122.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts