%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\gabri\Dropbox\AgroModel\Meteorology\ArroyitoDatos2022.csv
%
% Auto-generated by MATLAB on 2022-03-08

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = [3, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["fecha", "tmpmax", "tmpmed", "tmpmin", "dpmax", "dpmed", "dpmin", "hrmax", "hrmed", "hrmin", "speedmax", "speedmed", "speedmin", "presshigh", "presslow", "precip"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "fecha", "InputFormat", "MM/dd/yyyy","DateTimeFormat","yyyy-MM-dd");
opts = setvaropts(opts, ["tmpmax", "tmpmed", "tmpmin", "dpmax", "dpmed", "dpmin", "hrmax", "hrmed", "hrmin", "speedmax", "speedmed", "speedmin", "presshigh", "presslow", "precip"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["tmpmax", "tmpmed", "tmpmin", "dpmax", "dpmed", "dpmin", "hrmax", "hrmed", "hrmin", "speedmax", "speedmed", "speedmin", "presshigh", "presslow", "precip"], "ThousandsSeparator", ",");

% Import the data
climahistorico = readtable("Meteorology\ArroyitoDatos2022.csv", opts);


%% Clear temporary variables
clear opts