%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\gabri\Dropbox\AgroModel\Meteorology\Datos de ET0 from Manfredi.xlsx
%    Worksheet: data
%
% Auto-generated by MATLAB on 2022-05-24

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 1);

% Specify sheet and range
opts.Sheet = "data";
opts.DataRange = "D2:D152";

% Specify column names and types
opts.VariableNames = "EtoPM";
opts.VariableTypes = "double";

% Import the data
tablaET0 = readtable("C:\Users\gabri\Dropbox\AgroModel\Meteorology\Datos de ET0 from Manfredi.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts