%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\gabri\Dropbox\AgroModel\Meteorology\Solar radiation 011020 to 310521.csv
%
% Auto-generated by MATLAB on 2022-03-08

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["YEAR", "DOY", "mjm2", "Month", "Day"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
radhist = readtable("C:\Users\gabri\Dropbox\AgroModel\Meteorology\Solar radiation 011020 to 310521.csv", opts);


%% Clear temporary variables
clear opts