%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\gabri\Dropbox\AgroModel\Meteorology\clima20_21.xlsx
%    Worksheet: Clima20-21
%
% Auto-generated by MATLAB on 2022-07-27

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = "Clima20-21";
opts.DataRange = "A2:E459";

% Specify column names and types
opts.VariableNames = ["AO", "MES", "DIA", "RadiacMJM2", "EtoPM"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Import the data
clima2021 = readtable("C:\Users\gabri\Dropbox\AgroModel\Meteorology\clima20_21.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

fechas = datetime(table2array(clima2021(:,1:3)),'Format','dd-MMM-yyyy');

climahistorico_rad2020 = timetable(fechas,clima2021.RadiacMJM2,clima2021.EtoPM,...
    'VariableNames',{'RAD','ET0'});