%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\gabri\Dropbox\AgroModel\Meteorology\clima_futuro.csv
%
% Auto-generated by MATLAB on 2022-03-08

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["TMINC", "TMEDC", "TMAXC", "RADWm2", "LLUVIAMM", "TTDC", "FECHA", "RADmjm2"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "datetime", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "FECHA", "InputFormat", "dd-MM-yy","DatetimeFormat","yyyy-MM-dd");

% Import the data
climafuturo = readtable("C:\Users\gabri\Dropbox\AgroModel\Meteorology\clima_futuro.csv", opts);


%% Clear temporary variables
clear opts