%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\gabri\Dropbox\AgroModel\Meteorology\Solar radiation 011020 to 310521.csv
%
% Auto-generated by MATLAB on 23-Feb-2022 17:48:31

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["YEAR", "DOY", "mjm2", "Month", "Day"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Solarradiation011020to310521 = readtable("C:\Users\gabri\Dropbox\AgroModel\Meteorology\Solar radiation 011020 to 310521.csv", opts);

%% Convert to output type
solar_rad = table2array(Solarradiation011020to310521);

%% Clear temporary variables
clear opts