%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\gabri\Dropbox\AgroModel\Meteorology\lluvias.xlsx
%    Worksheet: Weather Data
%
% Auto-generated by MATLAB on 2022-05-11

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = "Weather Data";
opts.DataRange = "A2:B223";

% Specify column names and types
opts.VariableNames = ["datetime", "precip"];
opts.VariableTypes = ["datetime", "double"];

% Specify variable properties
opts = setvaropts(opts, "datetime", "InputFormat", "");

% Import the data
lluvias = readtable("C:\Users\gabri\Dropbox\AgroModel\Meteorology\lluvias.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts