%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\gabri\Dropbox\AgroModel\fechasiembra_2020.xlsx
%    Worksheet: Maiz
%
% Auto-generated by MATLAB on 2022-03-08

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = "Maiz";
opts.DataRange = "A1:H31";

% Specify column names and types
opts.VariableNames = ["campo", "lat", "long", "Cultivo", "variedad", "antecesor", "FS", "RtoTn"];
opts.VariableTypes = ["categorical", "char", "char", "char", "char", "char", "char", "char"];

% Specify variable properties
opts = setvaropts(opts, ["lat", "long", "antecesor", "RtoTn"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["campo", "lat", "long", "antecesor", "RtoTn"], "EmptyFieldRule", "auto");
% opts = setvaropts(opts, "FS", "InputFormat", "");

% Import the data
fechasiembra = readtable("C:\Users\gabri\Dropbox\AgroModel\fechasiembra_2020-2021.xlsx", opts, "UseExcel", false);

%% Convert to output type
fechasiembra = table2cell(fechasiembra);
numIdx = cellfun(@(x) ~isnan(str2double(x)), fechasiembra);
fechasiembra(numIdx) = cellfun(@(x) {str2double(x)}, fechasiembra(numIdx));


%% Clear temporary variables
clear opts


%% Matriz de coordenadas decimles y fechas de siembra
% limpieza de lat y longitud
mat_coord_m = [];
mat_fs_m = [];
for i = 2 : size(fechasiembra,1)
    tmp = cell2mat(fechasiembra(i,2));
    lat = str2angle( strcat(tmp(1:8),'"S'));
    tmp = cell2mat(fechasiembra(i,3));
    lon = str2angle( strcat(tmp(1:8),'"W'));
    t = datetime(cell2mat(fechasiembra(i,7)),'InputFormat','dd-MMM-yyyy','Format','yyyy-MM-dd');
    mat_coord_m = [mat_coord_m ; lat,lon];
    mat_fs_m = [mat_fs_m ; t];
end
% cell_fs_m = cell(0);
% for i = 1:size(mat_fs_s,1)
%     cell_fs_s{i}=mat_fs_s(i,:);
% end

clear tmp lat lon t