prof_raiz = zeros(size_datos);                                             % profundidad de la ra�z en tiempo i 
aud_1_h = zeros(size_datos);
aud_2_h = zeros(size_datos);
aud_3_h = zeros(size_datos);
aud_4_h = zeros(size_datos);
aud_5_h = zeros(size_datos);
aud_6_h = zeros(size_datos);
aud_7_h = zeros(size_datos);
aud_8_h = zeros(size_datos);
aut_1_h = zeros(size_datos);
aut_2_h = zeros(size_datos);
aut_3_h = zeros(size_datos);
aut_4_h = zeros(size_datos);
aut_5_h = zeros(size_datos);
aut_6_h = zeros(size_datos);
aut_7_h = zeros(size_datos);
aut_8_h = zeros(size_datos);
p_au_h = zeros(size_datos);

bi = zeros(size_datos);                                                    % biomasa a tiempo i
bt = zeros(size_datos);                                                    % biomasa acumulada a tiempo i
ici = zeros(size_datos);
rend = zeros(size_datos);
ct = zeros(size_datos);                                                    % porcentaje de ctertura en tiempo i
ceh_h = zeros(size_datos);
ceh_pc_h = zeros(size_datos);
cehr_h = zeros(size_datos);
t_eur_h = zeros(size_datos);
eur_act_h = zeros(size_datos);
ddp_h = zeros(size_datos);
tra_h = zeros(size_datos);
esc_h = zeros(size_datos);
eva_h = zeros(size_datos);
perc_h = zeros(size_datos);
dren_h = zeros(size_datos);
ppef_h = zeros(size_datos);
FCCH_h = ones(size_datos);
