%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\gabri\Dropbox\AgroModel\Meteorology\clima_total.csv
%
% Auto-generated by MATLAB on 16-Feb-2022 19:37:54

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "FECHA", "TMAXHC", "TMEDHC", "TMINHC", "DMAXHC", "DMEDHC", "DMINHC", "LLUVIAHMM", "TMINFC", "TMEDFC", "TMAXFC", "RADFWM2", "LLUVIAFMM", "TTDC", "RADFMJM2"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["FECHA", "TMINFC", "TMEDFC", "TMAXFC", "RADFWM2", "LLUVIAFMM", "TTDC", "RADFMJM2"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["FECHA", "TMINFC", "TMEDFC", "TMAXFC", "RADFWM2", "LLUVIAFMM", "TTDC", "RADFMJM2"], "ThousandsSeparator", ",");

% Import the data
climatotal = readtable("C:\Users\gabri\Dropbox\AgroModel\Meteorology\clima_total.csv", opts);

%% Convert to output type
climatotal = table2array(climatotal);

%% Clear temporary variables
clear opts